### ISSUE TITLE
What is the license on the code?

### ISSUE THREAD

**Issue by joshdance** [metafizzy/logo.pizza#1]
What is the license on the code? Couldn't find it in the readme file.

**Comment by desandro** [comment]
All logo SVG code is owned by Metafizzy or clients you have purchased the logo. All rights reserved

Everything else is MIT License. Have at it. Learn, use, remix, etc. Please don't whole-sale rip off the site cause that would be lame.

**Comment by joshdance** [comment]
Awesome. Thanks!
