### ISSUE TITLE
How do I deploy logo.pizza locally?

### ISSUE THREAD

**Issue by Evanto** [metafizzy/logo.pizza#3]
Hi, thank you for this awesome project! Could you please list the main steps to deploy this website locally? I tried, but when I open `index.html`, I don't see the logos, their pages, and Isotope doesn't work. Could it be because of bower? Web console log: [https://gist.github.com/Evanto/bbbedc6989577d8b2688eb30b00e3234](url)

**Comment by desandro** [comment]
Hello!

1. this repo does not include images in `img/`, so people can't easily try to re-sell the logos on a separate site
2. Yes, you'll need to do a `bower install`.

**Comment by Evanto** [comment]
@desandro Thank you for your reply! I installed Bower and Isotope now works. I have my own pics to load, but what should I do with them to make the logo pages work? If I just add my .jpg image to some random folder, like add my file 3.jpg to the img/gorilla-step folder, the `http://localhost:8080/gorilla-step` page has only `Cannot GET /gorilla-step` text on it. What should I do to make it work? Thank you!

**Comment by desandro** [comment]
look through `data/*.yml` files to see the content that's generated.
